### ISSUE TITLE
Provider authentication not compatible with changes in Boundary 0.2.0

### ISSUE THREAD

**Issue by evanravenelle** [hashicorp/terraform-provider-boundary#106]
It looks like Boundary 0.2.0 broke the TF Boundary provider.  I upgraded my Boundary controller to 0.2.0 recently and now TF builds are failing to authenticate to Boundary, and wont run unless I remove the Boundary configuration.  

### Terraform Version
Tried with both 0.14.8 and 0.15.1

Boundary provider version: 1.0.1

### Affected Resource(s)
Boundary provider -- unable to authenticate after upgrading Boundary controller to 0.2.0

### Terraform Configuration Files
```
provider "boundary" {
  auth_method_id = var.auth_method_id
  addr = "https://redacted:9200"
  password_auth_method_login_name = "redacted"
  password_auth_method_password   = "redacted"
}


resource "boundary_scope" "project" {
  name                   = var.project_name
  description            = var.project_description
  scope_id               = var.scope_id
  auto_create_admin_role = true

}

```

### Debug Output
```
boundary_scope.project: Creating...
╷
│ Error: error creating scope: {"kind":"Unauthenticated","message":"Unauthenticated, or invalid token."}
│
│   with boundary_scope.project,
│   on main.tf line 29, in resource "boundary_scope" "project":
│   29: resource "boundary_scope" "project" {
│
╵
```

### Expected Behavior
Terraform should have authenticated successfully and created the project.

### Actual Behavior
Terraform failed to authenticate.  This appears to be due to a change in the Boundary controller auth method.  The Boundary CLI client version 0.1.8 also fails on authentication (it appears to authenticate but returns no values in the response).

### Steps to Reproduce
1. Be running Boundary 0.2.0 on the Controller
1.  Create a TF config with Boundary provider and resources
2. terraform plan
3. terraform apply

### Important Factoids
Upgraded Boundary controller and workers to 0.2.0

**Comment by therealhanlin** [comment]
Same thing here. No changes in the TF files, upgrade the controller to 0.2.0 and it just stopped working.

**Comment by evanravenelle** [comment]
> Same thing here. No changes in the TF files, upgrade the controller to 0.2.0 and it just stopped working.

I'm going to leave this issue open because the release version of the provider is still broken, but building the provider from source has fixed the issue for me.  @therealhanlin

**Comment by therealhanlin** [comment]
> > Same thing here. No changes in the TF files, upgrade the controller to 0.2.0 and it just stopped working.
> 
> I'm going to leave this issue open because the release version of the provider is still broken, but building the provider from source has fixed the issue for me. @therealhanlin

Thanks for the tip man. I'll try it out.

**Comment by malnick** [comment]
Sorry for the tardy response on this! I'm taking a look this morning and will update this issue as soon as I have remediation.

**Comment by malnick** [comment]
Hi all, can you confirm you're using the provider version `1.0.2` which was published approx. 11 days ago? 

https://registry.terraform.io/providers/hashicorp/boundary/latest

**Comment by evanravenelle** [comment]
@malnick Hi Jeff, it seems as this was simply a case of poor timing.  I posted just before the new version was published--then tried building from source just after, not realizing the new version had been published.  I have since switched back to the TF repository version 1.0.2 and can confirm it is working for me.  Thanks!
