### ISSUE TITLE
Docs say title case is supported for type in `boundary_host_catalog` when it isn't

### ISSUE THREAD

**Issue by jacobmammoliti** [hashicorp/terraform-provider-boundary#115]
The provider docs say title case is supported [here](https://registry.terraform.io/providers/hashicorp/boundary/latest/docs/resources/host_catalog#required) but it does not work. Looks like we have to use `static`. You get the error shown below:

```
boundary_host_catalog.static: Creating...
╷
│ Error: invalid type provided
│ 
│   with boundary_host_catalog.static,
│   on main.tf line 75, in resource "boundary_host_catalog" "static":
│   75: resource "boundary_host_catalog" "static" {
```

Either, support needs to be added or docs need to be updated.

### Terraform Version

```bash
$ terraform -v         
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/boundary v1.0.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- boundary_host_catalog

### Terraform Configuration Files
```hcl
resource "boundary_host_catalog" "static" {
  name     = var.boundary_host_catalog
  type     = "Static"
  scope_id = boundary_scope.project.id
}
```

### Expected Behavior
This should accept the title case of `Static` based on docs.

### Actual Behavior
The error is shown posted above.

### Steps to Reproduce
Define the `boundary_host_catalog` resource and pass the type with `Static`

**Comment by malnick** [comment]
Thanks for opening this, the type has indeed changed to `static` (non-title-case). We'll open a PR to fix this on the provider, thank you!

**Comment by malnick** [comment]
PR for fixing this in our docs: https://github.com/hashicorp/terraform-provider-boundary/pull/121
