### ISSUE TITLE
Unable to use tolist or tomap on Boundary Group resource

### ISSUE THREAD

**Issue by djdta** [hashicorp/terraform-provider-boundary#117]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```terrform v1.0.0```

### Affected Resource(s)
Please list the resources as a list, for example:

- resource "boundary_group"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
```
resource "boundary_group" "example" {
  name        = var.groups # This is a list of groups to create
  description = "This is a group for the crs secuirty group"
  scope_id    = boundary_scope.org.id
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Been able to create more than one group at a time

### Actual Behavior
What actually happened?

Cannot pass a set of strings to this or a list for strings into this resource

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create list variable
2. Run terraform plan 
3. Then see the error

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by AntPAllen** [comment]
Have you tried doing this with a foreach?

```terraform
resource "boundary_group" "example" {
  for_each = toset(var.groups)
  name        = each.key
  description = "This is a group for the crs secuirty group"
  scope_id    = boundary_scope.org.id
}
```

**Comment by djdta** [comment]
I will that thanks :)

**Comment by djdta** [comment]
Issue fixed from AntPAllen :)
