### ISSUE TITLE
Recovery KMS HCL stop working after upgrade from 1.0.6 to 1.0.7

### ISSUE THREAD

**Issue by vhatsura** [hashicorp/terraform-provider-boundary#209]
### Terraform Version

1.1.9

### Provider Version

1.0.7

### Affected Resource(s)

Provider itself

### Terraform Configuration Files

```hcl
provider "boundary" {
  addr             = var.boundary_address
  recovery_kms_hcl = <<EOT
kms "awskms" {
	purpose    = "recovery"
	key_id     = "global_recovery"
  region     = "${var.region}"
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  kms_key_id = "${module.aws-kms.kms_boundary_recovery_key_id}"
}
EOT
}
```

### Actual Behavior

Terraform apply failed with the following error:

```
│ Error: error reading wrappers from "recovery_kms_hcl": Error configuring kms: plugin is nil
│ 
│   with provider["registry.terraform.io/hashicorp/boundary"],
│   on providers.tf line 63, in provider "boundary":
│   63: provider "boundary" {
```

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-181

**Comment by louisruch** [comment]
This has not been resolved looking into our build process to address

**Comment by louisruch** [comment]
Sorry for the long turn around on this issue. This should now be resolved with https://github.com/hashicorp/terraform-provider-boundary/releases/tag/v1.0.9
