### ISSUE TITLE
Not able to create a global admin

### ISSUE THREAD

**Issue by puneetmathur-87** [hashicorp/terraform-provider-boundary#218]
Hi there,

I am trying to configure the boundary from gobal scope admin using terraform but as soon as I create a new org under global scope  the subsequent resource creation requests are failing with no permission. 

I have provided the all permission on all types for the global user I am using in terraform provider but still it doesn't.

I am trying to find out if the user gets the global access permissions for all orgs we create under global scope or not?

**Comment by PPacent** [comment]
Hi @puneetmathur-87, when you create a scope in Terraform you can use the [auto_create_admin_role](https://registry.terraform.io/providers/hashicorp/boundary/latest/docs/resources/scope#auto_create_admin_role) argument to create an admin role in the scope by default and add the user running TF. Can you let us know if this resolves the issue you're seeing?
