### ISSUE TITLE
Create Azure/AWS Dynamic Host Catalogs

### ISSUE THREAD

**Issue by valeriocapponi** [hashicorp/terraform-provider-boundary#227]
### Terraform Version
1.2.3

### Affected Resource(s)
NONE

### Expected Behavior
Be able to set dynamic host catalogs for azure and aws

### Actual Behavior
Looks like is not possible with the Terraform provider or anyway not mentioned in documentation (https://learn.hashicorp.com/tutorials/boundary/azure-host-catalogs)

**Comment by serkansahinBE** [comment]
Hey @sswati0 any updates? It would be great to create dynamic host catalogs from Terraform 🙏

**Comment by PPacent** [comment]
Hi @valeriocapponi - AWS and Azure dynamic host catalogs and dynamic host sets can be configured using the Boundary Terraform Provider's [host_catalog_plugin](https://registry.terraform.io/providers/hashicorp/boundary/latest/docs/resources/host_catalog_plugin) and [host_set_plugin](https://registry.terraform.io/providers/hashicorp/boundary/latest/docs/resources/host_set_plugin) resources. You can learn more about this at the linked pages. Please let us know if you have any other outstanding questions.
