### ISSUE TITLE
error creating credential library in provider version 1.1.4 (works on 1.0.12)

### ISSUE THREAD

**Issue by maheimstaden** [hashicorp/terraform-provider-boundary#353]
Hi,

I am following https://github.com/hashicorp/learn-boundary-azure-sql-database.git guide to integrating Boundary with Vault.

I have an issue with this resource (works on 1.0.12 but not on the 1.1.4)

resource "boundary_credential_library_vault" "database" {
  name                = "database"
  description         = "Vault credential library for developer database access"
  credential_store_id = boundary_credential_store_vault.vault.id
  path                = local.boundary_creds_path
  http_method         = "GET"
}

What I get is:

Error: error creating credential library: {"kind":"InvalidArgument", "message":"Error in provided request.", "details":{"request_fields":[{"name":"credential_store_id", "description":"If included, type must match that of the credential store."}]}}
│ 
│   with module.vault_config.boundary_credential_library_vault.database,
│   on modules/vault/boundary.tf line 10, in resource "boundary_credential_library_vault" "database":
│   10: resource "boundary_credential_library_vault" "database" {

### Terraform Version
1.3.2

### Boundary Version
1.1.4

### Affected Resource(s)
- boundary_credential_library_vault

### Terraform Configuration Files
```hcl

terraform {
  required_version = ">= 1.0.0"
  backend "azurerm" {}

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0"
    }
    boundary = {
      source  = "hashicorp/boundary"
      version = "1.1.4"
    }
  }
}
...

resource "boundary_credential_store_vault" "vault" {
  name            = "vault"
  description     = "Vault credentials store"
  address         = local.vault_url
  tls_skip_verify = true
  token           = vault_token.boundary.client_token
  scope_id        = local.boundary_developer_scope
}

resource "boundary_credential_library_vault" "database" {
  name                = "database"
  description         = "Vault credential library for developer database access"
  credential_store_id = boundary_credential_store_vault.vault.id
  path                = local.boundary_creds_path
  http_method         = "GET"
}

```

### Expected Behavior
Resource is created

### Actual Behavior
```hcl
Error: error creating credential library: {"kind":"InvalidArgument", "message":"Error in provided request.", "details":{"request_fields":[{"name":"credential_store_id", "description":"If included, type must match that of the credential store."}]}}
│ 
│   with module.vault_config.boundary_credential_library_vault.database,
│   on modules/vault/boundary.tf line 10, in resource "boundary_credential_library_vault" "database":
│   10: resource "boundary_credential_library_vault" "database" {
```

### Steps to Reproduce
`terraform apply`

### Important Factoids
Works on 1.0.12

**Comment by macmiranda** [comment]
What's your Boundary controller version?

**Comment by maheimstaden** [comment]
Hi @macmiranda,

I am running 0.11.2-1 version, I will try to upgrade to 0.12 and let you know.

Thanks!

**Comment by maheimstaden** [comment]
Updated controller to 0.12.1-1 version and all seems to be working fine with 1.1.4 provider.

Thank you one more time.

Kr,
Michał.

**Comment by macmiranda** [comment]
Glad it helped 😊
