### ISSUE TITLE
website docs need to be regenerated for `boundary_worker`

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-boundary#454]
The registry docs show an example for a resource that does not exist:

https://registry.terraform.io/providers/hashicorp/boundary/latest/docs/resources/worker

This was fixed by PR: #438 but the docs do not reflect

```hcl
resource "boundary_self_managed_worker" "worker_led" {
  scope_id                    = "global"
  name                        = "worker 2"
  description                 = "self managed worker with worker led auth"
  worker_generated_auth_token = var.worker_generated_auth_token
}
```

<img width="983" alt="image" src="https://github.com/hashicorp/terraform-provider-boundary/assets/3812162/67dc65c5-63a1-453b-84d5-5d7484549b67">

**Comment by moduli** [comment]
I believe this has been addressed. I'm no longer seeing `boundary_self_managed_worker` at the link provided: https://registry.terraform.io/providers/hashicorp/boundary/latest/docs/resources/worker. I also confirmed that the relevant example/doc files do not contain `boundary_self_managed_worker`.
