### ISSUE TITLE
Documentation for boundary_target could use an example

### ISSUE THREAD

**Issue by lkd** [hashicorp/terraform-provider-boundary#78]
### Terraform Version
N/A

### Affected Resource(s)
Documentation of

- boundary_target

### Expected Behavior
It'd be really nice to mention that the "type" it expects maps to `boundary targets create tcp`, emphasizing `tcp`. Because all the other uses of "type" use the value `static`, it was trivial for me to get confused.

### Actual Behavior
I kept trying to build a `resource "boundary_target" {type="static"}` which was legitimately refused with a cryptic-ish message: `Error: invalid type provided` .

I had to double-check my "set up Boundary by hand" notes to understand why my muscle memory tripped me here.

### Steps to Reproduce
By inspection

### Important Factoids
I'd submit a pull request, but my employer doesn't permit signing CLAs at this time. I can open a github issue though.

**Comment by grantorchard** [comment]
Thanks for opening this - I came here to report the same issue. @jefferai I notice the docs are autogenerated, and pulling the description from [here](https://github.com/hashicorp/terraform-provider-boundary/blob/main/internal/provider/resource_target.go#L52). It would be trivial for me to update the description slightly, or as an alternative that is transparent to the end user we could default the type to "tcp". Let me know what you prefer.

**Comment by jefferai** [comment]
I don't think I'm following the suggestion. What update are you proposing?

**Comment by grantorchard** [comment]
Sorry, I should have been explicit.
Description: "The target resource type." > Description: "The target resource connection type. Currently only tcp is supported."

**Comment by jefferai** [comment]
The problem with saying "currently only tcp is supported" is that it's then easy to forget to update it when there are other types. So not sure this change is good. Or bad. Just neutral?

**Comment by grantorchard** [comment]
A simpler fix might be to include "type" in the [resource example](https://github.com/hashicorp/terraform-provider-boundary/blob/main/examples/resources/boundary_target/resource.tf#L52) for the documentation. That would avoid the explicit mention of supported options.

**Comment by louisruch** [comment]
Closing this since #88  merged, please re-open if needed
